apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: insight-read
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: insight-read-binding
subjects:
  - kind: ServiceAccount
    name: insight-sa
    namespace: insight
roleRef:
  kind: ClusterRole
  name: insight-read
  apiGroup: rbac.authorization.k8s.io